dist: xenial
cache: pip
env:
  global:
  - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  - SEGFAULT_SIGNALS=all
language: python
python: '3.7'
before_install:
- python --version
- uname -a
- lsb_release -a
install:
- pip --version
- pip install -e .
script:
- pyton setup.py test
notifications:
  email:
    on_success: never
    on_failure: always
