version: '3'
services:
  ner:
    image: linhdpostdata/hismetag
    expose:
      - "8080"
    restart: on-failure
  api:
    # image: linhdpostdata/poetrylab-api
    build: .
    environment:
    - NER_URI=http://ner:8080/api/rest/process/text
    - NER_HEALTH_URI=http://ner:8080/api/
    - "WORKERS=${WORKERS:-4}"
    - "TIMEOUT=${TIMEOUT:-120}"
    - PORT=5000
    expose:
      - "5000"
    ports:
      - "${API_PORT:-5000}:5000"
  web:
    image: linhdpostdata/poetrylab
    environment:
    - API_HOST=api
    - "API_PORT=${API_PORT:-5000}"
    ports:
      - "${PORT_WEB:-8000}:80"
